"""database tables

Revision ID: edcc56d6c8b7
Revises: 
Create Date: 2025-03-15 16:20:47.832060+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edcc56d6c8b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sales_aggregation',
    sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('units_sold', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('order_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('avg_unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('product_categories',
    sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('dim_time',
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('week_of_year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quarter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_weekend', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_holiday', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('street_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_login', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_orders', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lifetime_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('first_order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('average_order_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('days_between_orders', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('order_items',
    sa.Column('order_item_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('products',
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inventory_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profit_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('orders',
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shipping_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shipping_city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shipping_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shipping_zip', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('shipping_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processing_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('shipping_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('products')
    op.drop_table('order_items')
    op.drop_table('customers')
    op.drop_table('dim_time')
    op.drop_table('product_categories')
    op.drop_table('daily_sales_aggregation')

    # ### end Alembic commands ###